config/routes.rb
Rails.application.routes.draw do
  resources :links, :only => [:index, :create]
  get '/:slug', to: 'links#show', as: 'link'
  root 'links#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :clicks, class_name: "LinkClick"
  validates :slug, presence:true, uniqueness: true
  validates :url, presence: true, url: { public_suffix: true, message: "That's not a real URL" }

  after_initialize :generate_slug
  after_initialize :clean_url

  scope :top_100, -> {
    order('clicks_count DESC').limit(100)
  }

  def generate_slug
    self.slug = ApplicationController.helpers.generate_unique_short_slug(self.class, :slug) if self.slug.nil?
  end

  def clean_url
    self.url = "https://#{self.url}" if self.url.present? && !self.url.include?('//')
  end
end

app/models/link_click.rb
class LinkClick < ApplicationRecord
  belongs_to :link, dependent: :delete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def home
    render '/home'
  end

  def index
    @links = Link.top_100
  end

  def show
    url = @link.url

    @link.clicks.create(
      :user_agent   => request.user_agent,
      :referrer_url => request.referrer,
      :ip_address   => request.remote_ip,
      :country      => request.location.country,
    )

    @link.update(clicks_count: @link.clicks.count)

    redirect_to url
  end

  def create
    @link = Link.new(link_params)

    if @link.save
      LinksScrapeJob.perform_later(@link)
      render json: { notice: 'Yay!', link: @link, link_shortened: link_url(@link.slug) }
    else
      render json: { errors: @link.errors }, status: 404
    end
  end

  private
    def set_link
      @link = Link.find_by(:slug => params[:slug])
    end

    def link_params
      params.require(:link).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def generate_unique_short_slug(model, field)
    slug             = nil
    duplicates       = 0
    duplicates_limit = 3
    records_count    = model.count
    records_count    = 1 if records_count == 0
    digits           = (Math.log(records_count, 58) + 1).floor

    while slug.nil?
      slug = SecureRandom.base58(digits)

      if model.find_by(field => slug).present?
        slug = nil
        duplicates += 1
      end

      if duplicates == duplicates_limit
        duplicates = 0
        digits += 1
      end
    end

    return slug
  end

  def tr(key, variables = {})
    I18n.t key, variables
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiffl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-800">
    <div class="font-sans text-white relative">
      <%= render partial: '/nav' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for :link, url: links_path, method: 'POST', remote: true, html: {id: 'form_links_create', class: 'relative g:pb-12', 'data-error-msg': tr('form.error_message')} do |form| %>
  <div class="sm:flex">
    <%= form.text_field :url, placeholder: tr('form.placeholder'), class: 'input-field input-field:focus', autocomplete: 'off' %>
    <button
      type="submit"
      id="new_link_button"
      data-initial-msg="<%= tr 'form.button'  %>"
      data-submitting-msg="<%= tr 'form.button_saving'  %>"
      class="button button:focus button:hover mt-4 h-12 py-3 px-6 sm:w-auto sm:h-auto sm:mt-0 lg:mt-0 sm:ml-4"><%= tr 'form.button'  %></button>
  </div>
  <div id="error_explanation" class="error-message" style="opacity:0"></div>
<% end %>

app/views/links/_link.html.erb
<div class="link card md:w-1/2 lg:w-1/3">
  <a href="<%= link_url(link.slug) %>" target="_blank" class="card-inner hover:bg-gray-200">
    <div>
      <h3 class="mb-3 flex font-bold">
        <% if link.title.present? %>
            <% if link.logo_url.present? %>
              <div class="mr-3 w-12"><img class="rounded" height="30" width="30" src="<%= link.logo_url %>"/></div>
            <% end %>
            <%= link.title.truncate(75, separator: '...') %>
          </h3>
        <% else %>
          <%= link.url.truncate(35, separator: '...') %>
        <% end %>
      </h3>
      <p class="text-sm text-gray-700"><%= link.description.truncate(100, separator: '...') if link.description.present? %></p>
    </div>
    <div class="text-sm mt-auto flex text-gray-400 border-t border-gray-400 pt-3">
      <span class="mr-auto"><strong><%= link.clicks_count %></strong> <%= tr 'links.clicks' %></span>
      <span><%=raw tr 'links.created_ago', {time: time_ago_in_words(link.created_at)} %></span>
    </div>
  </a>
</div>

app/views/links/index.html.erb
<div class="container mx-auto py-24 px-6">
  <h1 class="header xl:text-5xl"><%= tr 'links.header' %></h1>
  <p class="subheader xl:text-2xl"><%= tr 'links.subheader' %></p>

  <div id="links_index" class="flex flex-wrap -mx-2">
    <% if @links.count > 0 %>
      <%= render partial: 'links/link', collection: @links %>
    <% else %>
      <div class="py-12 px-2"><%=raw tr 'links.none_found' %></div>
    <% end %>
  </div>
</div>